/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cifrado_des_aes;


import javax.swing.JOptionPane;

/**
 *
 * @author river
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Resultado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Cadena = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TipoCifrado = new javax.swing.JComboBox<>();
        Clave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Resultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 320, 120));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Resultado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        Cadena.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Cadena, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 320, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Texto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cifrado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 20));

        TipoCifrado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TipoCifrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DES", "AES 128", "AES 192", "AES 256" }));
        TipoCifrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoCifradoActionPerformed(evt);
            }
        });
        getContentPane().add(TipoCifrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 320, -1));

        Clave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 320, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Clave:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, 20));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Descifrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 150, 50));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cifrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 150, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Resultado.setText("");
        boolean Bandera = true;
        String checarClave = Clave.getText();
        int TipCifrado = TipoCifrado.getSelectedIndex();
        int NumeroCaractere = 0;
        if (checarClave.length() != 8 && TipCifrado == 0) {
            Bandera = false;
            NumeroCaractere = 8;
        } else if (checarClave.length() != 16 && TipCifrado == 1) {
            Bandera = false;
            NumeroCaractere = 16;
        } else if (checarClave.length() != 24 && TipCifrado == 2) {
            Bandera = false;
            NumeroCaractere = 24;
        } else if (checarClave.length() != 32 && TipCifrado == 3) {
            Bandera = false;
            NumeroCaractere = 32;
        }
        if (!Bandera) {
            JOptionPane.showMessageDialog(null, "La longitud de la clave no es valida debe tener: " + NumeroCaractere + " Caracteres", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (Clave.getText().isEmpty() || Cadena.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Clave y Texto a cifrar no pueden estar vacios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        Cifrado_DES_AES log = new Cifrado_DES_AES();
        Resultado.setText(log.Cifrado(Cadena.getText(), Clave.getText(), TipoCifrado.getSelectedIndex()));


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Resultado.setText("");
        boolean Bandera = true;
        String Clavechecar = Clave.getText();
        int TipCifrado = TipoCifrado.getSelectedIndex();
        int NumeroCaracteres = 0;
        if (Clavechecar.length() != 8 && TipCifrado == 0) {
            Bandera = false;
            NumeroCaracteres = 8;
        } else if (Clavechecar.length() != 16 && TipCifrado == 1) {
            Bandera = false;
            NumeroCaracteres = 16;
        } else if (Clavechecar.length() != 24 && TipCifrado == 2) {
            Bandera = false;
            NumeroCaracteres = 24;
        } else if (Clavechecar.length() != 32 && TipCifrado == 3) {
            Bandera = false;
            NumeroCaracteres = 32;
        }
        if (!Bandera) {
            JOptionPane.showMessageDialog(null, "La longitud de la clave no es valida debe tener: " + NumeroCaracteres + " Caracteres", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (Clave.getText().isEmpty() || Cadena.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Clave y Texto a cifrar no pueden estar vacios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        Cifrado_DES_AES log = new Cifrado_DES_AES();
        Resultado.setText(log.Descifrar(Cadena.getText(), Clave.getText(), TipoCifrado.getSelectedIndex()));

    }//GEN-LAST:event_jButton4ActionPerformed

    private void TipoCifradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoCifradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoCifradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cadena;
    private javax.swing.JTextField Clave;
    private javax.swing.JTextField Resultado;
    private javax.swing.JComboBox<String> TipoCifrado;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
